# low latency
policy_path: "assets/ckpts/x2_finetune_policy/policy.onnx"

compliance_flag_value: 1.0 # 0.0 to disable compliance, 1.0 to enable compliance
compliance_flag_threshold: 10.0 # 10.0 ~ 20.0
future_steps: [0, 1, 2, 3, 4, -1, -2, -4, -8, -12, -16] # student_future_steps from training; exported ONNX expects len=11
motion_source: "udp"
vr_req_addr: "tcp://127.0.0.1:28701"
vr_rep_addr: "tcp://127.0.0.1:28702"
vr_ctrl_addr: "tcp://127.0.0.1:28703"
vr_low_watermark: 5 # when to request frame
vr_high_watermark: 5 # when to stop requesting frame; should be >= low_watermark
vr_chunk_frames: 1 # how many frames to request each time
vr_inflight_lifetime_steps: 0 # how many steps to wait before considering an inflight request as failed
root_linacc_history_steps: [0, 1, 2, 3, 4, 8, 12, 16, 20]
root_angvel_history_steps: [0, 1, 2, 3, 4, 8, 12, 16, 20]
projected_gravity_history_steps: [0, 1, 2, 3, 4, 8, 12, 16, 20]
joint_pos_history_steps: [0, 1, 2, 3, 4, 8, 12, 16, 20]
joint_vel_history_steps: [0, 1, 2, 3, 4, 8, 12, 16, 20]
prev_action_steps: 8
switch_tail_keep_steps: 8 # keep old ref tail on motion switch; final keep is max(this, abs(min(future_steps)))

motions:
  - name: "Subject_61_F_3"
    path: "/home/liuguoxing/Documents/dataset_new/retarget_x2_npz/AMASS/BMLmovi/Subject_61_F_MoSh/Subject_61_F_3_stageii.npz"
    start: 0
    end: -1
  - name: "EKUT_300_PushStandTrans_06"
    path: "assets/data/x2_motions/EKUT_300_PushStandTrans_06.npz"
    start: 0
    end: -1
  - name: "EKUT_300_PushStandStraight_09"
    path: "assets/data/x2_motions/EKUT_300_PushStandStraight_09.npz"
    start: 0
    end: -1
  - name: "Transitions_mazen_c3d_punchboxing_jumpinplace"
    path: "assets/data/x2_motions/Transitions_mazen_c3d_punchboxing_jumpinplace.npz"
    start: 0
    end: -1
  - name: "GRAB_s10_camera_takepicture_3"
    path: "assets/data/x2_motions/GRAB_s10_camera_takepicture_3.npz"
    start: 0
    end: -1
  - name: "GRAB_s5_stanfordbunny_pass_1"
    path: "assets/data/x2_motions/GRAB_s5_stanfordbunny_pass_1.npz"
    start: 0
    end: -1
  - name: "KIT_167_walking_slow03"
    path: "assets/data/x2_motions/KIT_167_walking_slow03.npz"
    start: 0
    end: -1
  - name: "KIT_378_push_recovery_left02"
    path: "assets/data/x2_motions/KIT_378_push_recovery_left02.npz"
    start: 0
    end: -1
  - name: "BMLrub_rub038_0017_lifting_light1"
    path: "assets/data/x2_motions/BMLrub_rub038_0017_lifting_light1.npz"
    start: 0
    end: -1
  - name: "BMLrub_rub103_0014_knocking2"
    path: "assets/data/x2_motions/BMLrub_rub103_0014_knocking2.npz"
    start: 0
    end: -1
  - name: "BMLrub_rub077_0018_lifting_light2"
    path: "assets/data/x2_motions/BMLrub_rub077_0018_lifting_light2.npz"
    start: 0
    end: -1
  - name: "ACCAD_Male2Walking_c3d_B14_Walk_turn_right_45_t2"
    path: "assets/data/x2_motions/ACCAD_Male2Walking_c3d_B14_Walk_turn_right_45_t2.npz"
    start: 0
    end: -1
  - name: "CNRS_283_-12_R_2"
    path: "assets/data/x2_motions/CNRS_283_-12_R_2.npz"
    start: 0
    end: -1
motion_clips:
  - name: "default"
    joint_pos: [-0.28, 0.0, 0.0, 0.5, -0.23, 0.0, -0.28, 0.0, 0.0, 0.5, -0.23, 0.0, 0.0, 0.0, 0.0, 0.35, 0.16, 0.0, 0.87, 0.0, 0.0, 0.0, 0.35, -0.16, 0.0, 0.87, 0.0, 0.0, 0.0]
    root_quat: [1., 0., 0., 0.]
    root_pos: [0.0, 0.0, 0.78]

action_clip: 10.0

action_joint_names: [
  "left_hip_pitch_joint", "left_hip_roll_joint", "left_hip_yaw_joint", "left_knee_joint", "left_ankle_pitch_joint", "left_ankle_roll_joint",
  "right_hip_pitch_joint", "right_hip_roll_joint", "right_hip_yaw_joint", "right_knee_joint", "right_ankle_pitch_joint", "right_ankle_roll_joint",
  "waist_yaw_joint", "waist_pitch_joint", "waist_roll_joint",
  "left_shoulder_pitch_joint", "left_shoulder_roll_joint", "left_shoulder_yaw_joint", "left_elbow_joint",
  "left_wrist_yaw_joint", "left_wrist_pitch_joint", "left_wrist_roll_joint",
  "right_shoulder_pitch_joint", "right_shoulder_roll_joint", "right_shoulder_yaw_joint", "right_elbow_joint",
  "right_wrist_yaw_joint", "right_wrist_pitch_joint", "right_wrist_roll_joint"
]

action_scale: [
  0.5, 0.5, 0.5, 0.5, 0.5, 0.5,
  0.5, 0.5, 0.5, 0.5, 0.5, 0.5,
  0.5, 0.5, 0.5,
  1.0, 1.0, 1.0, 1.0,
  1.0, 1.0, 1.0,
  1.0, 1.0, 1.0, 1.0,
  1.0, 1.0, 1.0
]

dataset_joint_names: [
  "left_hip_pitch_joint", "left_hip_roll_joint", "left_hip_yaw_joint", "left_knee_joint", "left_ankle_pitch_joint", "left_ankle_roll_joint",
  "right_hip_pitch_joint", "right_hip_roll_joint", "right_hip_yaw_joint", "right_knee_joint", "right_ankle_pitch_joint", "right_ankle_roll_joint",
  "waist_yaw_joint", "waist_pitch_joint", "waist_roll_joint",
  "left_shoulder_pitch_joint", "left_shoulder_roll_joint", "left_shoulder_yaw_joint", "left_elbow_joint",
  "left_wrist_yaw_joint", "left_wrist_pitch_joint", "left_wrist_roll_joint",
  "right_shoulder_pitch_joint", "right_shoulder_roll_joint", "right_shoulder_yaw_joint", "right_elbow_joint",
  "right_wrist_yaw_joint", "right_wrist_pitch_joint", "right_wrist_roll_joint"
]

kps_real: [
  # left leg
  99.09842777666113, 99.09842777666113, 40.17923847137318, 99.09842777666113, 28.50124619574858, 28.50124619574858,
  # right leg
  99.09842777666113, 99.09842777666113, 40.17923847137318, 99.09842777666113, 28.50124619574858, 28.50124619574858,
  # waist
  40.17923847137318, 28.50124619574858, 28.50124619574858,
  # left arm
  14.25062309787429, 14.25062309787429, 14.25062309787429, 14.25062309787429, 14.25062309787429, 14.25062309787429, 14.25062309787429,
  # right arm
  14.25062309787429, 14.25062309787429, 14.25062309787429, 14.25062309787429, 14.25062309787429, 14.25062309787429, 14.25062309787429,
]

kds_real: [
  # left leg
  6.3088018534966395, 6.3088018534966395, 2.5578897650279457, 6.3088018534966395, 1.814445686584846, 1.814445686584846,
  # right leg
  6.3088018534966395, 6.3088018534966395, 2.5578897650279457, 6.3088018534966395, 1.814445686584846, 1.814445686584846,
  # waist
  2.5578897650279457, 1.814445686584846, 1.814445686584846,
  # left arm
  0.907222843292423, 0.907222843292423, 0.907222843292423, 0.907222843292423, 0.907222843292423, 0.907222843292423, 0.907222843292423,
  # right arm
  0.907222843292423, 0.907222843292423, 0.907222843292423, 0.907222843292423, 0.907222843292423, 0.907222843292423, 0.907222843292423,
]
